### Universe

In [2]:
import pandas as pd

In [3]:
universe_file_path = './data/snp500.csv'
df = pd.read_csv(universe_file_path, index_col=False)

In [3]:
df

    Symbol                 Name                  Sector
0      MMM                   3M             Industrials
1      AOS          A. O. Smith             Industrials
2      ABT  Abbott Laboratories             Health Care
3     ABBV               AbbVie             Health Care
4     ABMD              Abiomed             Health Care
..     ...                  ...                     ...
500    YUM          Yum! Brands  Consumer Discretionary
501   ZBRA   Zebra Technologies  Information Technology
502    ZBH        Zimmer Biomet             Health Care
503   ZION        Zions Bancorp              Financials
504    ZTS               Zoetis             Health Care

[505 rows x 3 columns]

In [4]:
tickers = df['Symbol'].tolist()
tickers

['MMM',
 'AOS',
 'ABT',
 'ABBV',
 'ABMD',
 'ACN',
 'ATVI',
 'ADM',
 'ADBE',
 'AAP',
 'AMD',
 'AES',
 'AFL',
 'A',
 'APD',
 'AKAM',
 'ALK',
 'ALB',
 'ARE',
 'ALGN',
 'ALLE',
 'LNT',
 'ALL',
 'GOOGL',
 'GOOG',
 'MO',
 'AMZN',
 'AMCR',
 'AEE',
 'AAL',
 'AEP',
 'AXP',
 'AIG',
 'AMT',
 'AWK',
 'AMP',
 'ABC',
 'AME',
 'AMGN',
 'APH',
 'ADI',
 'ANSS',
 'ANTM',
 'AON',
 'APA',
 'AAPL',
 'AMAT',
 'APTV',
 'ANET',
 'AJG',
 'AIZ',
 'T',
 'ATO',
 'ADSK',
 'ADP',
 'AZO',
 'AVB',
 'AVY',
 'BKR',
 'BLL',
 'BAC',
 'BBWI',
 'BAX',
 'BDX',
 'BRK.B',
 'BBY',
 'BIO',
 'TECH',
 'BIIB',
 'BLK',
 'BK',
 'BA',
 'BKNG',
 'BWA',
 'BXP',
 'BSX',
 'BMY',
 'AVGO',
 'BR',
 'BRO',
 'BF.B',
 'CHRW',
 'CDNS',
 'CZR',
 'CPB',
 'COF',
 'CAH',
 'KMX',
 'CCL',
 'CARR',
 'CTLT',
 'CAT',
 'CBOE',
 'CBRE',
 'CDW',
 'CE',
 'CNC',
 'CNP',
 'CDAY',
 'CERN',
 'CF',
 'CRL',
 'SCHW',
 'CHTR',
 'CVX',
 'CMG',
 'CB',
 'CHD',
 'CI',
 'CINF',
 'CTAS',
 'CSCO',
 'C',
 'CFG',
 'CTXS',
 'CLX',
 'CME',
 'CMS',
 'KO',
 'CTSH',
 'CL',
 'CMCSA',
 'CMA',
 'CAG',
 'COP',
 'ED',
 'STZ',
 'CPRT',
 'GLW',
 'CTVA',
 'COST',
 'CTRA',
 'CCI',
 'CSX',
 'CMI',
 'CVS',
 'DHI',
 'DHR',
 'DRI',
 'DVA',
 'DE',
 'DAL',
 'XRAY',
 'DVN',
 'DXCM',
 'FANG',
 'DLR',
 'DFS',
 'DISCA',
 'DISCK',
 'DISH',
 'DG',
 'DLTR',
 'D',
 'DPZ',
 'DOV',
 'DOW',
 'DTE',
 'DUK',
 'DRE',
 'DD',
 'DXC',
 'EMN',
 'ETN',
 'EBAY',
 'ECL',
 'EIX',
 'EW',
 'EA',
 'LLY',
 'EMR',
 'ENPH',
 'ETR',
 'EOG',
 'EFX',
 'EQIX',
 'EQR',
 'ESS',
 'EL',
 'ETSY',
 'RE',
 'EVRG',
 'ES',
 'EXC',
 'EXPE',
 'EXPD',
 'EXR',
 'XOM',
 'FFIV',
 'FB',
 'FAST',
 'FRT',
 'FDX',
 'FIS',
 'FITB',
 'FRC',
 'FE',
 'FISV',
 'FLT',
 'FMC',
 'F',
 'FTNT',
 'FTV',
 'FBHS',
 'FOXA',
 'FOX',
 'BEN',
 'FCX',
 'GPS',
 'GRMN',
 'IT',
 'GNRC',
 'GD',
 'GE',
 'GIS',
 'GM',
 'GPC',
 'GILD',
 'GPN',
 'GL',
 'GS',
 'HAL',
 'HBI',
 'HAS',
 'HCA',
 'PEAK',
 'HSIC',
 'HES',
 'HPE',
 'HLT',
 'HOLX',
 'HD',
 'HON',
 'HRL',
 'HST',
 'HWM',
 'HPQ',
 'HUM',
 'HBAN',
 'HII',
 'IBM',
 'IEX',
 'IDXX',
 'INFO',
 'ITW',
 'ILMN',
 'INCY',
 'IR',
 'INTC',
 'ICE',
 'IFF',
 'IP',
 'IPG',
 'INTU',
 'ISRG',
 'IVZ',
 'IPGP',
 'IQV',
 'IRM',
 'JBHT',
 'JKHY',
 'J',
 'SJM',
 'JNJ',
 'JCI',
 'JPM',
 'JNPR',
 'KSU',
 'K',
 'KEY',
 'KEYS',
 'KMB',
 'KIM',
 'KMI',
 'KLAC',
 'KHC',
 'KR',
 'LHX',
 'LH',
 'LRCX',
 'LW',
 'LVS',
 'LEG',
 'LDOS',
 'LEN',
 'LNC',
 'LIN',
 'LYV',
 'LKQ',
 'LMT',
 'L',
 'LOW',
 'LUMN',
 'LYB',
 'MTB',
 'MRO',
 'MPC',
 'MKTX',
 'MAR',
 'MMC',
 'MLM',
 'MAS',
 'MA',
 'MTCH',
 'MKC',
 'MCD',
 'MCK',
 'MDT',
 'MRK',
 'MET',
 'MTD',
 'MGM',
 'MCHP',
 'MU',
 'MSFT',
 'MAA',
 'MRNA',
 'MHK',
 'TAP',
 'MDLZ',
 'MPWR',
 'MNST',
 'MCO',
 'MS',
 'MSI',
 'MSCI',
 'NDAQ',
 'NTAP',
 'NFLX',
 'NWL',
 'NEM',
 'NWSA',
 'NWS',
 'NEE',
 'NLSN',
 'NKE',
 'NI',
 'NSC',
 'NTRS',
 'NOC',
 'NLOK',
 'NCLH',
 'NRG',
 'NUE',
 'NVDA',
 'NVR',
 'NXPI',
 'ORLY',
 'OXY',
 'ODFL',
 'OMC',
 'OKE',
 'ORCL',
 'OGN',
 'OTIS',
 'PCAR',
 'PKG',
 'PH',
 'PAYX',
 'PAYC',
 'PYPL',
 'PENN',
 'PNR',
 'PBCT',
 'PEP',
 'PKI',
 'PFE',
 'PM',
 'PSX',
 'PNW',
 'PXD',
 'PNC',
 'POOL',
 'PPG',
 'PPL',
 'PFG',
 'PG',
 'PGR',
 'PLD',
 'PRU',
 'PTC',
 'PEG',
 'PSA',
 'PHM',
 'PVH',
 'QRVO',
 'QCOM',
 'PWR',
 'DGX',
 'RL',
 'RJF',
 'RTX',
 'O',
 'REG',
 'REGN',
 'RF',
 'RSG',
 'RMD',
 'RHI',
 'ROK',
 'ROL',
 'ROP',
 'ROST',
 'RCL',
 'SPGI',
 'CRM',
 'SBAC',
 'SLB',
 'STX',
 'SEE',
 'SRE',
 'NOW',
 'SHW',
 'SPG',
 'SWKS',
 'SNA',
 'SO',
 'LUV',
 'SWK',
 'SBUX',
 'STT',
 'STE',
 'SYK',
 'SIVB',
 'SYF',
 'SNPS',
 'SYY',
 'TMUS',
 'TROW',
 'TTWO',
 'TPR',
 'TGT',
 'TEL',
 'TDY',
 'TFX',
 'TER',
 'TSLA',
 'TXN',
 'TXT',
 'COO',
 'HIG',
 'HSY',
 'MOS',
 'TRV',
 'DIS',
 'TMO',
 'TJX',
 'TSCO',
 'TT',
 'TDG',
 'TRMB',
 'TFC',
 'TWTR',
 'TYL',
 'TSN',
 'USB',
 'UDR',
 'ULTA',
 'UAA',
 'UA',
 'UNP',
 'UAL',
 'UPS',
 'URI',
 'UNH',
 'UHS',
 'VLO',
 'VTR',
 'VRSN',
 'VRSK',
 'VZ',
 'VRTX',
 'VFC',
 'VIAC',
 'VTRS',
 'V',
 'VNO',
 'VMC',
 'WRB',
 'GWW',
 'WAB',
 'WBA',
 'WMT',
 'WM',
 'WAT',
 'WEC',
 'WFC',
 'WELL',
 'WST',
 'WDC',
 'WU',
 'WRK',
 'WY',
 'WHR',
 'WMB',
 'WLTW',
 'WYNN',
 'XEL',
 'XLNX',
 'XYL',
 'YUM',
 'ZBRA',
 'ZBH',
 'ZION',
 'ZTS']

### Yahoo Historical data (2016-2023) and Earning Calendars

In [5]:
## Params
start_date = '2016-01-01'
end_date = '2023-08-31'

In [6]:
tickers =['MSFT', 'AAPL', 'MDB']

In [ ]:
import yfinance as yf

open_result = pd.DataFrame()
close_result = pd.DataFrame()
high_result = pd.DataFrame()
low_result = pd.DataFrame()
volume_result = pd.DataFrame()
earnings_calendars = {}

for i in range(len(tickers)):
    ticker = tickers[i]
    #print(ticker, i, len(tickers))
    ticker_data = yf.Ticker(ticker)

    #historical data
    historical_data = ticker_data.history(start=start_date, end=end_date)
    #open = historical_data['Open']
    close = historical_data['Close']
    #high = historical_data['High']
    #low = historical_data['Low']
    #volume = historical_data['Volume']
    #open_result[ticker] = open
    close_result[ticker] = close
    #high_result[ticker] = high
    #low_result[ticker] = low
    #volume_result[ticker] = volume

In [28]:
close_result

,MMM,AOS,ABT,ABBV,ABMD,ACN,ATVI,ADM,ADBE,AAP,...,WLTW,WYNN,XEL,XLNX,XYL,YUM,ZBRA,ZBH,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-04 00:00:00-05:00,113.048523,33.202068,37.160885,41.186237,85.239998,89.974754,35.592754,28.809200,91.970001,140.337891,...,NaN,61.980740,28.352652,NaN,32.759193,44.992352,66.489998,93.003998,22.009640,44.828045
2016-01-05 00:00:00-05:00,113.541328,33.016586,37.152229,41.014664,85.000000,90.443031,35.138618,29.130730,92.339996,139.379135,...,NaN,63.152424,28.638554,NaN,32.750130,44.880207,64.820000,94.940605,21.770666,45.529819
2016-01-06 00:00:00-05:00,111.254501,32.362957,36.840607,41.021812,85.300003,90.266327,34.807484,28.423363,91.019997,135.691879,...,NaN,59.880779,28.940350,NaN,32.341530,44.562431,62.230000,95.351700,21.136171,45.539299
2016-01-07 00:00:00-05:00,108.544174,30.781895,35.957676,40.900269,81.919998,87.615585,34.315502,27.748142,89.110001,137.194427,...,NaN,54.247807,29.051540,NaN,31.506205,43.042118,59.410000,93.159279,20.501677,44.154720
2016-01-08 00:00:00-05:00,108.174561,29.686659,35.204590,39.785004,84.580002,86.767349,33.785683,27.643644,87.849998,134.180084,...,NaN,52.039684,28.733862,NaN,31.206579,42.456436,59.250000,92.766464,20.270945,43.509850
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-24 00:00:00-04:00,98.500000,68.800003,103.750000,146.630005,NaN,314.140015,91.410004,80.330002,512.429993,67.910004,...,NaN,95.489998,56.500019,NaN,99.328522,128.935928,265.920013,114.072281,34.470001,181.559998
2023-08-25 00:00:00-04:00,98.949997,69.750000,104.209999,146.690002,NaN,318.760010,91.660004,80.830002,525.059998,64.080002,...,NaN,95.480003,57.064922,NaN,100.843613,129.135010,268.390015,114.990288,34.130001,182.820007
2023-08-28 00:00:00-04:00,104.120003,70.709999,102.790001,147.429993,NaN,320.910004,91.769997,80.870003,529.919983,65.629997,...,NaN,96.790001,57.332504,NaN,101.491516,129.309998,269.920013,117.275330,34.900002,186.979996
2023-08-29 00:00:00-04:00,105.570000,71.860001,103.870003,147.589996,NaN,323.450012,91.980003,81.610001,540.570007,66.940002,...,NaN,98.070000,57.431610,NaN,101.960007,128.899994,273.489990,118.971649,35.439999,192.770004
2023-08-30 00:00:00-04:00,104.449997,72.300003,104.410004,148.320007,NaN,323.250000,91.980003,80.750000,545.359985,68.099998,...,NaN,99.389999,57.164024,NaN,103.489998,130.100006,279.109985,119.979454,34.990002,192.699997

In [16]:
close_result.index = close_result.index.strftime("%Y-%m-%d")

In [17]:
close_result

                  MSFT        AAPL         MDB
Date
2016-01-04   48.797729   24.009062         NaN
2016-01-05   49.020344   23.407412         NaN
2016-01-06   48.129871   22.949337         NaN
2016-01-07   46.455784   21.980774         NaN
2016-01-08   46.598263   22.097000         NaN
...                ...         ...         ...
2023-08-24  319.970001  176.380005  360.750000
2023-08-25  322.980011  178.610001  363.459991
2023-08-28  323.700012  180.190002  354.320007
2023-08-29  328.410004  184.119995  367.380005
2023-08-30  328.790009  187.649994  375.519989

[1928 rows x 3 columns]

File to use in strategy

In [9]:
open_file_path = './data/open_price.csv'
close_file_path = './data/close_price.csv'
high_file_path = './data/high_price.csv'
low_file_path = './data/low_price.csv'
volume_file_path = './data/volume.csv'

In [29]:
close_result.to_csv(close_file_path)

In [31]:
msft = yf.Ticker('MSFT')
data = msft.get_earnings_dates(limit=60)
data.index

DatetimeIndex(['2024-07-23 06:00:00-04:00', '2024-04-23 06:00:00-04:00',
               '2024-01-22 16:00:00-05:00', '2024-01-22 05:00:00-05:00',
               '2023-10-23 06:00:00-04:00', '2023-07-25 12:00:00-04:00',
               '2023-04-25 12:00:00-04:00', '2023-01-24 11:00:00-05:00',
               '2022-10-25 12:00:00-04:00', '2022-07-26 12:00:00-04:00',
               '2022-04-26 12:00:00-04:00', '2022-01-25 11:00:00-05:00',
               '2021-10-26 12:00:00-04:00', '2021-07-27 12:00:00-04:00',
               '2021-04-27 12:00:00-04:00', '2021-01-26 11:00:00-05:00',
               '2020-10-27 12:00:00-04:00', '2020-07-22 12:00:00-04:00',
               '2020-04-29 12:00:00-04:00', '2020-01-29 11:00:00-05:00',
               '2019-10-23 12:00:00-04:00', '2019-07-18 12:00:00-04:00',
               '2019-04-24 12:00:00-04:00', '2019-01-30 11:00:00-05:00',
               '2018-10-24 12:00:00-04:00', '2018-07-19 12:00:00-04:00',
               '2018-04-26 12:00:00-04:00', '2018-01-31 11:00:00-05:00',
               '2017-10-26 12:00:00-04:00', '2017-07-20 12:00:00-04:00',
               '2017-04-27 12:00:00-04:00', '2017-01-26 11:00:00-05:00',
               '2016-10-20 12:00:00-04:00', '2016-07-19 12:00:00-04:00',
               '2016-04-21 12:00:00-04:00', '2016-01-28 11:00:00-05:00',
               '2015-10-22 12:00:00-04:00', '2015-07-21 12:00:00-04:00',
               '2015-04-23 12:00:00-04:00', '2015-01-26 11:00:00-05:00',
               '2014-10-23 12:00:00-04:00', '2014-07-22 00:00:00-04:00',
               '2014-04-24 00:00:00-04:00', '2014-01-23 00:00:00-05:00',
               '2013-10-24 00:00:00-04:00', '2013-07-18 00:00:00-04:00',
               '2013-04-18 00:00:00-04:00', '2013-01-24 00:00:00-05:00',
               '2012-10-18 00:00:00-04:00', '2012-07-19 00:00:00-04:00',
               '2012-04-19 00:00:00-04:00', '2012-01-19 00:00:00-05:00',
               '2011-10-20 00:00:00-04:00', '2011-07-21 00:00:00-04:00',
               '2011-04-28 00:00:00-04:00', '2011-01-27 00:00:00-05:00',
               '2010-10-28 00:00:00-04:00', '2010-07-22 00:00:00-04:00',
               '2010-04-22 00:00:00-04:00', '2010-01-28 00:00:00-05:00'],
              dtype='datetime64[ns, America/New_York]', name='Earnings Date', freq=None)

In [5]:
import yfinance as yf

earnigns_date_by_ticker = {}
for i in range(len(tickers)):
    print(i, len(tickers))
    ticker = tickers[i]
    ticker_data = yf.Ticker(ticker)
    earnings_data = ticker_data.get_earnings_dates(limit=60)
    if earnings_data is not None:
        earnigns_date_by_ticker[ticker] = earnings_data.index

0 505
1 505
2 505
3 505
4 505
5 505
6 505
7 505
8 505
9 505
10 505
11 505
12 505
13 505
14 505
15 505
16 505
17 505
18 505
19 505
20 505
21 505
22 505
23 505
24 505
25 505
26 505
27 505
28 505
29 505
30 505
31 505
32 505
33 505
34 505
35 505
36 505
37 505
38 505
39 505
40 505
41 505
42 505
43 505
44 505
45 505
46 505
47 505
48 505
49 505
50 505
51 505
52 505
53 505
54 505
55 505
56 505
57 505
58 505
59 505
60 505
61 505
62 505
63 505
64 505
- BRK.B: No earnings dates found, symbol may be delisted
65 505
66 505
67 505
68 505
69 505
70 505
71 505
72 505
73 505
74 505
75 505
76 505
77 505
78 505
79 505
80 505
- BF.B: No earnings dates found, symbol may be delisted
81 505
82 505
83 505
84 505
85 505
86 505
87 505
88 505
89 505
90 505
91 505
92 505
93 505
94 505
95 505
96 505
97 505
98 505
99 505
100 505
101 505
102 505
103 505
104 505
105 505
106 505
107 505
108 505
109 505
110 505
111 505
112 505
113 505
114 505
115 505
116 505
117 505
118 505
119 505
120 505
121 505
122 505
123 505
124 505
125 505
126 505
127 505
128 505
129 505
130 505
131 505
132 505
133 505
134 505
135 505
136 505
137 505
138 505
139 505
140 505
141 505
142 505
143 505
144 505
145 505
146 505
147 505
148 505
149 505
150 505
151 505
152 505
153 505
154 505
155 505
156 505
157 505
158 505
159 505
160 505
161 505
162 505
163 505
164 505
165 505
166 505
167 505
168 505
169 505
170 505
171 505
172 505
173 505
174 505
175 505
176 505
177 505
178 505
179 505
180 505
181 505
182 505
183 505
184 505
185 505
186 505
187 505
188 505
189 505
190 505
191 505
192 505
193 505
194 505
195 505
196 505
197 505
198 505
199 505
200 505
201 505
202 505
203 505
204 505
205 505
- FOX: No earnings dates found, symbol may be delisted
206 505
207 505
208 505
209 505
210 505
211 505
212 505
213 505
214 505
215 505
216 505
217 505
218 505
219 505
220 505
221 505
222 505
223 505
224 505
225 505
226 505
227 505
228 505
229 505
230 505
231 505
232 505
233 505
234 505
235 505
236 505
237 505
238 505
239 505
240 505
241 505
242 505
243 505
244 505
245 505
246 505
247 505
248 505
249 505
250 505
251 505
252 505
253 505
254 505
255 505
256 505
257 505
258 505
259 505
260 505
261 505
262 505
263 505
264 505
265 505
266 505
267 505
268 505
269 505
270 505
271 505
272 505
273 505
274 505
275 505
276 505
277 505
278 505
279 505
280 505
281 505
282 505
283 505
284 505
285 505
286 505
287 505
288 505
289 505
290 505
291 505
292 505
293 505
294 505
295 505
296 505
297 505
298 505
299 505
300 505
301 505
302 505
303 505
304 505
305 505
306 505
307 505
308 505
309 505
310 505
311 505
312 505
313 505
314 505
315 505
316 505
317 505
318 505
319 505
320 505
321 505
322 505
323 505
324 505
325 505
326 505
327 505
328 505
329 505
330 505
331 505
332 505
- NWS: No earnings dates found, symbol may be delisted
333 505
334 505
335 505
336 505
337 505
338 505
339 505
340 505
341 505
342 505
343 505
344 505
345 505
346 505
347 505
348 505
349 505
350 505
351 505
352 505
353 505
354 505
355 505
356 505
357 505
358 505
359 505
360 505
361 505
362 505
363 505
364 505
365 505
366 505
367 505
368 505
369 505
370 505
371 505
372 505
373 505
374 505
375 505
376 505
377 505
378 505
379 505
380 505
381 505
382 505
383 505
384 505
385 505
386 505
387 505
388 505
389 505
390 505
391 505
392 505
393 505
394 505
395 505
396 505
397 505
398 505
399 505
400 505
401 505
402 505
403 505
404 505
405 505
406 505
407 505
408 505
409 505
410 505
411 505
412 505
413 505
414 505
415 505
416 505
417 505
418 505
419 505
420 505
421 505
422 505
423 505
424 505
425 505
426 505
427 505
428 505
429 505
430 505
431 505
432 505
433 505
434 505
435 505
436 505
437 505
438 505
439 505
440 505
441 505
442 505
443 505
444 505
445 505
446 505
447 505
448 505
449 505
450 505
451 505
452 505
453 505
454 505
455 505
456 505
457 505
458 505
459 505
460 505
461 505
462 505
463 505
464 505
465 505
466 505
467 505
468 505
469 505
470 505
471 505
472 505
473 505
474 505
475 505
476 505
477 505
478 505
479 505
480 505
481 505
482 505
483 505
484 505
485 505
486 505
487 505
488 505
489 505
490 505
491 505
492 505
493 505
494 505
495 505
496 505
497 505
498 505
499 505
500 505
501 505
502 505
503 505
504 505

In [6]:
for ticker in earnigns_date_by_ticker:
    print(ticker)

MMM
AOS
ABT
ABBV
ABMD
ACN
ATVI
ADM
ADBE
AAP
AMD
AES
AFL
A
APD
AKAM
ALK
ALB
ARE
ALGN
ALLE
LNT
ALL
GOOGL
GOOG
MO
AMZN
AMCR
AEE
AAL
AEP
AXP
AIG
AMT
AWK
AMP
ABC
AME
AMGN
APH
ADI
ANSS
ANTM
AON
APA
AAPL
AMAT
APTV
ANET
AJG
AIZ
T
ATO
ADSK
ADP
AZO
AVB
AVY
BKR
BLL
BAC
BBWI
BAX
BDX
BBY
BIO
TECH
BIIB
BLK
BK
BA
BKNG
BWA
BXP
BSX
BMY
AVGO
BR
BRO
CHRW
CDNS
CZR
CPB
COF
CAH
KMX
CCL
CARR
CTLT
CAT
CBOE
CBRE
CDW
CE
CNC
CNP
CDAY
CERN
CF
CRL
SCHW
CHTR
CVX
CMG
CB
CHD
CI
CINF
CTAS
CSCO
C
CFG
CTXS
CLX
CME
CMS
KO
CTSH
CL
CMCSA
CMA
CAG
COP
ED
STZ
CPRT
GLW
CTVA
COST
CTRA
CCI
CSX
CMI
CVS
DHI
DHR
DRI
DVA
DE
DAL
XRAY
DVN
DXCM
FANG
DLR
DFS
DISCA
DISCK
DISH
DG
DLTR
D
DPZ
DOV
DOW
DTE
DUK
DRE
DD
DXC
EMN
ETN
EBAY
ECL
EIX
EW
EA
LLY
EMR
ENPH
ETR
EOG
EFX
EQIX
EQR
ESS
EL
ETSY
RE
EVRG
ES
EXC
EXPE
EXPD
EXR
XOM
FFIV
FB
FAST
FRT
FDX
FIS
FITB
FRC
FE
FISV
FLT
FMC
F
FTNT
FTV
FBHS
FOXA
BEN
FCX
GPS
GRMN
IT
GNRC
GD
GE
GIS
GM
GPC
GILD
GPN
GL
GS
HAL
HBI
HAS
HCA
PEAK
HSIC
HES
HPE
HLT
HOLX
HD
HON
HRL
HST
HWM
HPQ
HUM
HBAN
HII
IBM
IEX
IDXX
INFO
ITW
ILMN
INCY
IR
INTC
ICE
IFF
IP
IPG
INTU
ISRG
IVZ
IPGP
IQV
IRM
JBHT
JKHY
J
SJM
JNJ
JCI
JPM
JNPR
KSU
K
KEY
KEYS
KMB
KIM
KMI
KLAC
KHC
KR
LHX
LH
LRCX
LW
LVS
LEG
LDOS
LEN
LNC
LIN
LYV
LKQ
LMT
L
LOW
LUMN
LYB
MTB
MRO
MPC
MKTX
MAR
MMC
MLM
MAS
MA
MTCH
MKC
MCD
MCK
MDT
MRK
MET
MTD
MGM
MCHP
MU
MSFT
MAA
MRNA
MHK
TAP
MDLZ
MPWR
MNST
MCO
MS
MSI
MSCI
NDAQ
NTAP
NFLX
NWL
NEM
NWSA
NEE
NLSN
NKE
NI
NSC
NTRS
NOC
NLOK
NCLH
NRG
NUE
NVDA
NVR
NXPI
ORLY
OXY
ODFL
OMC
OKE
ORCL
OGN
OTIS
PCAR
PKG
PH
PAYX
PAYC
PYPL
PENN
PNR
PBCT
PEP
PKI
PFE
PM
PSX
PNW
PXD
PNC
POOL
PPG
PPL
PFG
PG
PGR
PLD
PRU
PTC
PEG
PSA
PHM
PVH
QRVO
QCOM
PWR
DGX
RL
RJF
RTX
O
REG
REGN
RF
RSG
RMD
RHI
ROK
ROL
ROP
ROST
RCL
SPGI
CRM
SBAC
SLB
STX
SEE
SRE
NOW
SHW
SPG
SWKS
SNA
SO
LUV
SWK
SBUX
STT
STE
SYK
SIVB
SYF
SNPS
SYY
TMUS
TROW
TTWO
TPR
TGT
TEL
TDY
TFX
TER
TSLA
TXN
TXT
COO
HIG
HSY
MOS
TRV
DIS
TMO
TJX
TSCO
TT
TDG
TRMB
TFC
TWTR
TYL
TSN
USB
UDR
ULTA
UAA
UA
UNP
UAL
UPS
URI
UNH
UHS
VLO
VTR
VRSN
VRSK
VZ
VRTX
VFC
VIAC
VTRS
V
VNO
VMC
WRB
GWW
WAB
WBA
WMT
WM
WAT
WEC
WFC
WELL
WST
WDC
WU
WRK
WY
WHR
WMB
WLTW
WYNN
XEL
XLNX
XYL
YUM
ZBRA
ZBH
ZION
ZTS

In [7]:
earnings_file_path = "./data/earnings_data.txt"
with open(earnings_file_path, "w") as fw:
    for ticker in earnigns_date_by_ticker:
        fw.write("%s:" % ticker)
        earnings_dates = earnigns_date_by_ticker[ticker].tolist()
        for i in range(len(earnings_dates)):
            if i == len(earnings_dates) - 1:
                fw.write("%s\n" % earnings_dates[i].strftime("%Y-%m-%d"))
            else:
                fw.write("%s," % earnings_dates[i].strftime("%Y-%m-%d"))